sudo: required
services:
  -docker

before_install:
  - docker build -t adityasharma369/docker-react -f Dockerfile.dev .

script:
  - docker run adityasharma369/docker-react npm run test -- --coverage