sudo: required
services:
 - docker

before_install:
 - docker build -t adityasharma369/docker-react -f Dockerfile.dev .

script:
 - docker run adityasharma369/docker-react npm run test -- --coverage


# deploy:
#  provider: elasticbeanstalk
#  region: "" 
#  app: ""
#  env: ""
#  bucket_name: "app-name"
#  on:
#   branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#   secure: "$AWS_SECRET_KEY"